### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by LandStander27** [codesyncapp/codesync-atom#16]
[Enter steps to reproduce:]

1. I just closed Atom and reopened it.

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Pro
**Thrown From**: [codesync](https://github.com/codesyncapp/codesync-atom) package 3.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At C:\Users\%USERNAME%\.atom\packages\codesync\lib\views.js:128

TypeError: Cannot read property 'endsWith' of undefined
    at Object.getElement (/packages/codesync/lib/views.js:128:78)
    at ViewRegistry.createView (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:327571)
    at ViewRegistry.getView (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:327036)
    at /packages/minimap/dist/main.js:1:3720
    at Map.forEach (<anonymous>)
    at /packages/minimap/dist/main.js:1:3696)
    at /packages/minimap/dist/main.js:1:67719
```

### Commands

```
     -0:25.2.0 application:reopen-project (div#add-projects-view.)
```

### Non-Core Packages

```
autocomplete-clang 0.13.1 
autocomplete-python 1.17.0 
build 0.70.0 
busy-signal 2.0.1 
codesync 3.1.1 
file-icons 2.1.47 
intentions 2.1.1 
kite 0.206.0 
language-ini 1.25.0 
linter 3.4.0 
linter-gcc2 0.8.8 
linter-ui-default 3.4.1 
minimap 4.40.0 
predawn-syntax 1.0.4 
tool-bar 1.4.4 
```

**Comment by Basit-qc** [comment]
Thank you for reporting the issue @LandStander27. Will you please upgrade to v3.2.0 and see if it has fixed the issue for you?
Much thanks in advance.

**Comment by LandStander27** [comment]
> Thank you for reporting the issue @LandStander27. Will you please upgrade to v3.2.0 and see if it has fixed the issue for you?
> Much thanks in advance.

Thanks! I will test it out in a few days because I'm not home at the moment
